### ISSUE TITLE
Create a proper config to avoid maintaining several branches for different networks

### ISSUE THREAD

**Issue by Dzeranov** [humanprotocol/humansubgraph#16]
Currently there are 2 different branches for 2 different networks:
`main` is for polygon
`rinkeby` is for rinkeby.
It's inconvenient to use because it's needed to push changes to both branches. And the number of branches that we need to maintain will increase as long as we add new networks.

**Comment by Charlie85270** [comment]
Closed with https://github.com/humanprotocol/hmt-escrow/pull/337
