### ISSUE TITLE
Automatically get new contract versions

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/humansubgraph#7]
When we push a new version of hmt-escrow ,it should automatically index the new abis on all the chains.

**Comment by foufrix** [comment]
Hi @posix4e,
After some chat with @Charlie85270, he's ready to work on this, so maybe no need to publish on gitcoin.
I talked with Saqib and the price for this task would be 1 eth.

**Comment by Charlie85270** [comment]
Hey @posix4e, 

Can you precise the issue ? 
Maybe I miss something but actually abis are not indexed ? 
Which abis should be indexed ? 

Thanks you, 

Charlie

**Comment by posix4e** [comment]
We should generate them from https://github.com/humanprotocol/hmt-escrow

**Comment by foufrix** [comment]
Hi @posix4e, There is no ABI JSON file in https://github.com/humanprotocol/hmt-escrow , only https://github.com/humanprotocol/hmt-escrow/blob/master/hmt_escrow/kvstore_abi.py but seems not to be updated since three years
They are all in the fortune app currently https://github.com/humanprotocol/fortune/tree/master/exchange/src/contracts (repeated in 4 folders exchange|launcher|recording-oracle|reputation-oracle/src/contracts)

Should ABI be moved to 1 place for clarification, no?

**Comment by posix4e** [comment]
It generates Abi files from the contract files

**Comment by foufrix** [comment]
Ok ! Need to generate for Escrow.sol EscrowFactory.sol and HMToken.sol  in https://github.com/humanprotocol/hmt-escrow/tree/master/contracts ? We need more or those are ok?

**Comment by Charlie85270** [comment]
Hey @posix4e , I have some questions : 

- When you say "indexed" you mean the need to indexed the ABIs on the graph or that the graph uses the latest version of ABIs ? 
- Currently, the person who deploys the new versions of the contracts with htm-escrow then comes to update by hand the ABIs in the graph repo, then updates the graph right? 

If I understand well we need to automatize this process ? 

I don't see exactly how do this technically technically? A pull request is created automatically with the new ABIs on the graph repo when deploying? 

Excuse me if this is not clear, I checked the htm-escrow repo but I don't do Python, I'm probably missing something.

**Comment by posix4e** [comment]
Grab time at about.me/posix4e and I’ll explain

**Comment by Charlie85270** [comment]
Closed with https://github.com/humanprotocol/hmt-escrow/pull/337
